<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cliente\Module'                        => __DIR__ . '/Module.php',
    'Cliente\Controller\IndexController' => __DIR__ . '/src/Cliente/Controller/IndexController.php',
//    'Cliente\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
//    'Cliente\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);