<h1>Alterar dados de Cliente</h1>
<br />

<?php 
    $form = $this->form;
    
    $form->setAttribute('action',$this->url('cliente/interna-pages', array('controller'=>'cliente-controller-index','action'=>'edit')));
    
    $form->prepare();
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('nome'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>