 <h1>Lista de Nome</h1>
<br/>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>

    <?php foreach ($this->dados as $data): ?>
        <tr>
            <td><?= $data->getId(); ?></td>
            <td><?= $data->getNome(); ?></td>
            <td>
                <a class="btn btn-success" href="<?php echo $this->url('interna-pages', array('controller'=>'cliente-controller-index','action'=>'edit','id'=>$data->getId())); ?>">Editar</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>
<br />

<?php echo $this->paginationControl($this->dados,'Sliding','paginator');?>