 <h2>Cadastro Cliente</h2>
<br/>

<p>
    <a class="btn btn-success" href="<?php echo $this->url('cliente/default-pages', array('controller'=>'cliente-controller-index','action'=>'new')); ?>">Novo Registro</a>
</p>
<hr/>
<br>
<?php 
    $form = $this->form;
    
    $form->setAttribute('action',$this->url('cliente/pesquisa-pages', array('controller'=>'cliente-controller-index','action'=>'pesquisa')));
    
    $form->prepare();
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('nome'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>
<hr/>
<br>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>

    <?php foreach ($this->dados as $data): ?>
        <tr>
            <td><?= $data->getId(); ?></td>
            <td><?= $data->getNome(); ?></td>
            <td>
                <a class="btn btn-success" href="<?php echo $this->url('cliente/interna-pages', array('controller'=>'cliente-controller-index','action'=>'edit','id'=>$data->getId())); ?>">Editar</a>
                <a class="btn btn-success" href="<?php echo $this->url('cliente/interna-pages', array('controller'=>'cliente-controller-index','action'=>'delete','id'=>$data->getId())); ?>">Deletar</a>

            </td>
        </tr>
    <?php endforeach; ?>

</table>
<br />

<?php echo $this->paginationControl($this->dados,'Sliding','paginator');?>