<div class="row">
    <h1><?php echo sprintf('Junior Oaks') ?></h1>
    <p><?php echo sprintf('Formado em Analise desenvolvimento de sistema, cursando pós-graduação puc-minas engenharia de software, trabalho a 8 anos com desenvolvimento web tendo como experiencia Linux, Apache, MySQL, PHP, shell scripts, HTML/XHTML, CSS, SOAP/REST, java, javascript, controle de version(svn), git.
Projetos, sistema de controle de acesso para provedor de internet algumas funcionalidades: cadastro de cliente, controle de fluxo, contrato, boleto, gerencia ssh fre-radius, integração mikrotik. 
CEO e desenvolvedor empresa SISGEW em projetos para órgão municipal: prefeitura, câmaras, escolas, secretarias.... Sistema para micro e pequenas empresas com sistema de gestão online e emissão de Nota Fiscal Eletronica, desenvolvido em php.') ?></p>
    <p><a class="btn btn-success btn-lg" href="http://www.junioroaks.com" target="_blank"><?php echo 'Junior Oaks' ?> &raquo;</a></p>
</div>